### PR TITLE
feat: connect llama 8b module to gui

### PR DESCRIPTION
**Pull request by Semuca**
## Description of changes
Adds the Llama 8B api to the GUI:
- Fixes issues with key storage
- Adds Llama 8B option to key storage
- Deletes duplicate push buttons
- Adds the ability to use the Llama API by abstracting the GPT code. Question: are the seperate query10.py and llama.py files necessary now?

Issue number: #31 
## Screenshots
image

### CODE REVIEW

**Comment by Semuca** [comment]
The linter seems like it's acting up- it's reading main instead of the branch I believe? I will investigate further on in the week, but I can confirm ruff check runs fine for this PR.
image

**Comment by sleepadept** [comment]
> Question: are the seperate query10.py and llama.py files necessary now?

Do you suggest we have one query.py that handles both gpt-4o and llama-8b?

**Comment by Semuca** [comment]
Possibly- that's what I've implemented here. The functionality is incredibly similar for both of them, minus a few key words. In short, the current version of the project only uses query.py- are there any notable differences you see between what query.py does and query10.py/llama.py?

**Comment by sleepadept** [comment]
> Possibly- that's what I've implemented here. The functionality is incredibly similar for both of them, minus a few key words. In short, the current version of the project only uses query.py- are there any notable differences you see between what query.py does and query10.py/llama.py?

I can't see any significant difference too. I can work on that either today or tomorrow for the integration.

**Review by sleepadept — APPROVED** [review]

**Pull request merged**
